1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.


In [6]:
import numpy as np
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print("Матрица 8x8 в шахматном порядке заполненная 0 и 1:")
print(Z)

Матрица 8x8 в шахматном порядке заполненный 0 и 1:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
import numpy as np
chess = np.indices((8, 8)).sum(axis=0) % 2
print("Матрица 8x8 в шахматном порядке заполненная 0 и 1:")
print(chess)

Матрица 8x8 в шахматном порядке заполненная 0 и 1:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
import numpy as np
print("Матрица 8x8 в шахматном порядке заполненная 0 и 1:")
x = np.array([[0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0], [0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0], [0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0], [0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0]])
print(x)

Матрица 8x8 в шахматном порядке заполненная 0 и 1:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange. 

In [9]:
import numpy as np
print("5x5 матрица со значениями в строках от 0 до 4:")
A = np.zeros((5,5)) # Матрица 5x5
A += np.arange(5) # Значение в строках от 0 до 4
print(A)

5x5 матрица со значениями в строках от 0 до 4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [10]:
import numpy as np
print("Массив 3x3x3 со случайными значениями:")
Z = np.random.random((3,3,3))
print(Z)

Массив 3x3x3 со случайными значениями:
[[[0.53912193 0.33400413 0.18036393]
  [0.89579973 0.18905429 0.8418447 ]
  [0.36634629 0.12747532 0.20804598]]

 [[0.49143853 0.06946983 0.86002714]
  [0.60299592 0.41611759 0.84694441]
  [0.49642648 0.43596258 0.41661586]]

 [[0.96986701 0.90591363 0.76655197]
  [0.30550307 0.87235667 0.12252385]
  [0.3302698  0.28055958 0.65604737]]]


1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [12]:
x = np.ones((10, 10))
print("Матрица с 0 внутри, и 1 на границах: ")
x[1:-1, 1:-1] = 0
print(x)

Матрица с 0 внутри, и 1 на границах: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
import numpy as np
print("Матрица с 0 внутри, и 1 на границах: ")
chess = np.array([[0]*7 for i in range(7)])  #создаем массив 8x8
for i in range(7):
    for j in range(7):
        if i == 0 or i == 6 or j == 0 or j == 6:
            chess[i][j] = 1
print(chess)

Матрица с 0 внутри, и 1 на границах: 
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [16]:
import numpy as np
arr = np.random.randint(1,10,10)
print("Неотсортированный массив: ",arr)
x = np.sort(arr)
x = x[::-1]
print("Отсортированный массив:    ", end='')
print(x)

Неотсортированный массив:  [7 9 3 7 2 3 6 5 2 9]
Отсортированный массив:    [9 9 7 7 6 5 3 3 2 2]


1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [18]:
import numpy as np
print("Матрица: ")
x = np.random.random((2, 2))
print(x)
print("Форма матрицы = ", x.shape)
print("Размер  матрицы = ",x.size)
print("Размерность  матрицы = ",x.ndim)

Матрица: 
[[0.33267598 0.65875655]
 [0.73088576 0.3753866 ]]
Форма матрицы =  (2, 2)
Размер  матрицы =  4
Размерность  матрицы =  2


2.3.1 Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [4]:
from math import sqrt
import pandas as pd
a = pd.Series([2, 4, 6, 8, 10])
b = pd.Series([20, 40, 60, 60, 100])
def evk_S(y, z):
   res = 0
   for i in range(len(y)):
       res += (y[i] - z[i]) ** 2
   return round(sqrt(res),2)
print("Евклидово расстояние: ",evk_S(a, b))

Евклидово расстояние:  123.85


2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets)

In [5]:
import pandas as pd
a = 'https://gist.githubusercontent.com/mistercrunch/7405007/raw/cc34e0e854a898456b0818b27da1add38268b099/cars.csv'
dataframe = pd.read_csv(a)
print(dataframe.head(10))

                      name  economy (mpg)  cylinders  displacement (cc)  \
0  AMC Ambassador Brougham           13.0          8              360.0   
1       AMC Ambassador DPL           15.0          8              390.0   
2       AMC Ambassador SST           17.0          8              304.0   
3         AMC Concord DL 6           20.2          6              232.0   
4           AMC Concord DL           18.1          6              258.0   
5           AMC Concord DL           23.0          4              151.0   
6              AMC Concord           19.4          6              232.0   
7              AMC Concord           24.3          4              151.0   
8              AMC Gremlin           18.0          6              232.0   
9              AMC Gremlin           19.0          6              232.0   

   power (hp)  weight (lb)  0-60 mph (s)  year  
0       175.0         3821          11.0    73  
1       190.0         3850           8.5    70  
2       150.0         3672 

2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [11]:
import pandas as pd
a = 'https://gist.githubusercontent.com/mistercrunch/7405007/raw/cc34e0e854a898456b0818b27da1add38268b099/cars.csv'
dataframe = pd.read_csv(a)
print("Первые несколько строк:")
print(dataframe.head(5))   #первые несколько строк
print("Последние несколько строк:")
print(dataframe.tail(2))    #последние несколько строк
print('Кол-во строк и столбцов:')
print(dataframe.shape,'\n')      #кол-во строк и столбцов
print("Статистика для числовых столбцов:")
print(dataframe.describe()) #статистика для числовых столбцов
print("Срез фрейма: ")
print(dataframe.iloc[1:4])  #срез фрейма
print("Отбор строки данных на основе некоторого условия: ")
print(dataframe[dataframe['name'] == 'AMC Gremlin'].head(20)) #отбор строки данных на основе некоторого условия

Первые несколько строк:
                      name  economy (mpg)  cylinders  displacement (cc)  \
0  AMC Ambassador Brougham           13.0          8              360.0   
1       AMC Ambassador DPL           15.0          8              390.0   
2       AMC Ambassador SST           17.0          8              304.0   
3         AMC Concord DL 6           20.2          6              232.0   
4           AMC Concord DL           18.1          6              258.0   

   power (hp)  weight (lb)  0-60 mph (s)  year  
0       175.0         3821          11.0    73  
1       190.0         3850           8.5    70  
2       150.0         3672          11.5    72  
3        90.0         3265          18.2    79  
4       120.0         3410          15.1    78  
Последние несколько строк:
             name  economy (mpg)  cylinders  displacement (cc)  power (hp)  \
404   Volvo 264GL           17.0          6              163.0       125.0   
405  Volvo Diesel           30.7          6     

3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.


In [12]:
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn import preprocessing
a = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(a) #читаем фрейм данных
x = np.array(dataframe['sepal_length_cm']) #делаем первый признак в массив
n = preprocessing.normalize([x]) #нормализация по методу минимакс
print("Нормализация по методу минимакс: ")
print(n,"\n","\n")
y = np.array(dataframe['sepal_width_cm']) #делаем второй признак в массив
m = zscore(y) #нормализация по методу Z-масштабирования
print("Нормализация по методу Z-масштабирования: ")
print(m)

Нормализация по методу минимакс: 
[[0.07056264 0.06779548 0.06502832 0.06364474 0.06917906 0.07471338
  0.06364474 0.06917906 0.06087757 0.06779548 0.07471338 0.0664119
  0.0664119  0.05949399 0.08024771 0.07886413 0.07471338 0.07056264
  0.07886413 0.07056264 0.07471338 0.07056264 0.06364474 0.07056264
  0.0664119  0.06917906 0.06917906 0.07194622 0.07194622 0.06502832
  0.0664119  0.07471338 0.07194622 0.07609697 0.06779548 0.06917906
  0.07609697 0.06779548 0.06087757 0.07056264 0.06917906 0.06226115
  0.06087757 0.06917906 0.07056264 0.0664119  0.07056264 0.06364474
  0.0733298  0.06917906 0.09685068 0.0885492  0.0954671  0.07609697
  0.08993278 0.07886413 0.08716562 0.06779548 0.09131636 0.07194622
  0.06917906 0.08163129 0.08301487 0.08439845 0.07748055 0.09269994
  0.07748055 0.08024771 0.08578203 0.07748055 0.08163129 0.08439845
  0.08716562 0.08439845 0.0885492  0.09131636 0.09408352 0.09269994
  0.08301487 0.07886413 0.07609697 0.07609697 0.08024771 0.08301487
  0.07471338 0.